@startuml
top to bottom direction
skinparam packageStyle rectangle

actor "Usuario" as User
actor "Atleta" as At
actor "Operador" as Op

' Herança entre atores
User <|-- Op
User <|-- At

rectangle "Sistema de Gestão das Olimpíadas" {
  
  usecase "HS01 - Autenticar" as AUTH

  usecase "HS02 - Realizar Inscrição" as RI
  usecase "HS03 - Vizualizar Atletas Inscritos" as CI
  usecase "HS04 - Visualizar Resultados" as VR

  usecase "HS05 - Gerenciar Competição" as GC
  usecase "HS06 - Cadastrar Competição" as C
  usecase "HS07 - Alterar Competição" as A
  usecase "HS08 - Cancelar Competição" as Can

  usecase "HS09 - Alocar Local" as AL
  usecase "HS10 - Registrar Resultados" as RR
  usecase "HS11 - Gerar Relatório de Medalhas" as GRM
  
  ' Relações
  At --> RI
  At --> CI

  User --> VR

  Op --> GC
  Op --> AL
  Op --> RR
  Op --> GRM
  
  ' Extends de Gerenciar Competicao (CRUD)
  C ..> GC : <<extend>>
  A ..> GC : <<extend>>
  Can ..> GC : <<extend>>
  
  ' Include de autenticação
  GC ..> AUTH : <<include>>
  AL ..> AUTH : <<include>>
  RR ..> AUTH : <<include>>
  GRM ..> AUTH : <<include>>
  RI ..> AUTH : <<include>>
  CI ..> AUTH : <<include>>
  
  ' Extends para regras
  C .> (HS12 - Verificar Data e Horário) : <<extends>>
  AL .> (HS13 - Verificar Disponibilidade Local) : <<extends>>
  RR .> (HS14 - Validar Pódio) : <<extends>>
  RI ..> (HS15 - Verificar País Representado) : <<include>>
}

@enduml
